### ISSUE TITLE
Running into ratelimits in slack_usergroup

### ISSUE THREAD

**Issue by svenwltr** [pablovarela/terraform-provider-slack#64]
Hello! We are using the provider for mapping the owners of our repositories to Slack groups. Since we have a good amount of repositories, we run into rate limits often.

This is the error we get:

```
╷
│ Error: couldn't get usergroups: slack rate limit exceeded, retry after 3s
│
│   with module.slack.slack_usergroup.prps["android-app"],
│   on ../modules/slack/terraform.tf line 48, in resource "slack_usergroup" "prps":
│   48: resource "slack_usergroup" "prps" {
│
╵
```

We are currently on version `1.1.6` and are managing about 150 groups.

I guess some sort of retry would be an option and we are willing to contribute, but want to discuss this issue first.

Relevant docs:

* https://api.slack.com/docs/rate-limits#headers
* https://pkg.go.dev/github.com/slack-go/slack#RateLimitedError

**Comment by pablovarela** [comment]
Hi! Apologies for the late response.

Sorry you are running into throttling issues. I have not tested the provider with so many groups. Some retries with a back-off algorithm sounds like a sensible solution. We should make it configurable  to allow setting the number of retries or the maximum waiting time for the call to succeed.

I am happy to implement it myself, but if you have something ready to go please feel free to contribute.

**Comment by svenwltr** [comment]
Hello! Thanks for the response.

We will look into it, but it might take a bit, because we are short on time. Might be easier for us to test, because we already have so much groups.

**Comment by svenwltr** [comment]
Hello! I finally got time to look into this. Unfortunately my initial idea is not working as expected, because Terraform is running the requests in parallel and therefore sleeping the time that is given via `RateLimitedError.RetryAfter` does not work.

Currently I have no approach solving this, which does not feel like a hack. For example waiting a static time could also fail now and then.

For completeness, the changes I tested with:

```diff
diff --git c/slack/resource_usergroup.go w/slack/resource_usergroup.go
index c3f3ea6..e10c38c 100644
--- c/slack/resource_usergroup.go
+++ w/slack/resource_usergroup.go
@@ -2,8 +2,10 @@ package slack
 
 import (
 	"context"
+	"errors"
 	"fmt"
 	"strings"
+	"time"
 
 	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
 	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
@@ -110,7 +112,11 @@ func resourceSlackUserGroupRead(ctx context.Context, d *schema.ResourceData, m i
 	client := m.(*slack.Client)
 	id := d.Id()
 	var diags diag.Diagnostics
-	userGroups, err := client.GetUserGroupsContext(ctx, slack.GetUserGroupsOptionIncludeUsers(true))
+	var userGroups []slack.UserGroup
+	err := slackRetry(func() (err error) {
+		userGroups, err = client.GetUserGroupsContext(ctx, slack.GetUserGroupsOptionIncludeUsers(true))
+		return err
+	})
 	if err != nil {
 		return diag.FromErr(fmt.Errorf("couldn't get usergroups: %w", err))
 	}
@@ -128,6 +134,27 @@ func resourceSlackUserGroupRead(ctx context.Context, d *schema.ResourceData, m i
 	return diags
 }
 
+func slackRetry(fn func() error) error {
+	const attempts = 3
+
+	var err error
+
+	for i := 0; i < attempts; i++ {
+		err = fn()
+		var rlerr *slack.RateLimitedError
+		switch {
+		case err == nil:
+			return nil
+		case errors.As(err, &rlerr):
+			time.Sleep(rlerr.RetryAfter)
+		default:
+			return err
+		}
+	}
+
+	return fmt.Errorf("failed after %d attempts: %w", attempts, err)
+}
+
 func findUserGroupByName(ctx context.Context, name string, includeDisabled bool, m interface{}) (slack.UserGroup, error) {
 	client := m.(*slack.Client)
 	userGroups, err := client.GetUserGroupsContext(ctx, slack.GetUserGroupsOptionIncludeDisabled(includeDisabled), slack.GetUserGroupsOptionIncludeUsers(true))
```

**Comment by rdsubhas** [comment]
Thank you so much @pablovarela for this terraform provider. We use it extensively, and we also noticed the same.

You are right – there is no 100% guaranteed solution because ofterraform parallelization. So anyways what we're doing right now is to just retry the terraform job until it succeeds.

Adding a simple retry (with static delay) would greatly reduce the number of retries we need to perform. So it's already a huge improvement over the current status quo.

If you are OK, I will raise a PR to use exponential backoff with jitter: https://pkg.go.dev/github.com/cenkalti/backoff/v4#example-Retry. It could be a bit more resilient to different variations of parallelism, as it would keep backing off with random jitters, but is still not 100% fool proof. A long term option would be to let the user themselves set the # of retries and delay, based on their own workloads, and let them tweak to the desired outcome.  But as you know, it's easier to exhaust the simple solutions (as you have mentioned before, static delay) before attempting the more complex ones. Please let me know what would you prefer: static timeout, or exponential backoff with jitter, or user-configured.

**Comment by smoya** [comment]
Please @pablovarela reopen this issue since it didn't get fix.
